#!/usr/bin/env python2
# Script to handle build time requests embedded in C code.
#
# Copyright (C) 2016-2024  Kevin O'Connor <kevin@koconnor.net>
#
# This file may be distributed under the terms of the GNU GPLv3 license.
import sys, os, subprocess, optparse, logging, shlex, socket, time, traceback
import json, zlib
sys.path.append('./klippy')
import msgproto
import pprint

from pprint import pprint

FILEHEADER = """
/* DO NOT EDIT! This is an autogenerated file. See scripts/buildcommands.py. */
syntax = "proto3";

import "helper.proto";
"""

def error(msg):
    sys.stderr.write(msg + "\n")
    sys.exit(-1)


class Field:
    def __init__(self, name : str, datatype : str):
        self.name = name
        self.datatype = datatype

class Message:
    def __init__(self, name : str, fields : list[Field]):
        self.name = name
        self.fields = fields
    def generate(self):
        msg = "message %s {\n" % self.name
        num = 1
        for field in self.fields:
            msg += "    %s %s = %d;\n" % (field.datatype, field.name, num)
            num += 1
        msg += "}\n"
        return msg


class ProtobufHandler:
    def __init__(self):
        self.commands = {}
        self.messages = [] 
        #self.parse_command("DECL_COMMAND_FLAGS dummy 0x01 identify_response offset=%u data=%.*s")
        #self.parse_command("DECL_COMMAND_FLAGS dummy 0x01 identify offset=%u count=%c")
    def parse_command(self, req):
        funcname, flags, msgname = req.split()[1:4]
        
        # parse each flag into a field
        msg = req.split(None, 3)[3]

        params = msgproto.lookup_params(msg)

        fields = []
        for (name, datatype) in params:
            #if isinstance(datatype, msgproto.PT_buffer):
                # add len field
                #fields.append(Field(name + "_len", "uint32"))
            prototype = datatype.protobuf()
            new_field = Field(name, prototype)
            fields.append(new_field)

        self.messages.append(Message(msgname, fields))

        pprint(params)

    def generate_code(self, options):
        out = "".join(msg.generate() for msg in self.messages)
        out += """
message klipperMessage {
    oneof content {"""
        num = 1
        for msg in self.messages:
            out += f"""
        {msg.name} {msg.name} = {num};"""
            num += 1
        out += """
    }
}
        
message klipperMessageSequence {
    repeated klipperMessage sequence = 1;
}"""
        return out




######################################################################
# Main code
######################################################################

def main():
    usage = "%prog [options] <cmd section file> <output.proto>"
    opts = optparse.OptionParser(usage)
    opts.add_option("-e", "--extra", dest="extra", default="",
                    help="extra version string to append to version")
    opts.add_option("-d", dest="write_dictionary",
                    help="file to write mcu protocol dictionary")
    opts.add_option("-t", "--tools", dest="tools", default="",
                    help="list of build programs to extract version from")
    opts.add_option("-v", action="store_true", dest="verbose",
                    help="enable debug messages")

    options, args = opts.parse_args()
    if len(args) != 2:
        opts.error("Incorrect arguments")
    incmdfile, outfile = args
    if options.verbose:
        logging.basicConfig(level=logging.DEBUG)

    handler = ProtobufHandler()

    # Parse request file
    f = open(incmdfile, 'r')
    data = f.read()
    f.close()
    for req in data.split('\n'):
        req = req.lstrip()
        if not req:
            continue
        cmd = req.split()[0]
        if cmd == "DECL_COMMAND_FLAGS":
            handler.parse_command(req)


    # Write protobuf file
    proto = "".join(FILEHEADER + handler.generate_code(options))
    p = open(outfile, "w")
    p.write(proto)
    p.close()


if __name__ == '__main__':
    main()
